version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: atlas_db
    env_file: .env
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - atlas_net

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: atlas_pgadmin
    env_file: .env
    ports:
      - 8080:80
    networks:
      - atlas_net

networks:
  atlas_net:

volumes:
  postgres_data:
